1.4  DOS VARIABLES INDEPENDIENTES: "NEOGOBERNANZA" y "GOBERNANZA EMBRIONARIA" derivadas del "Indice de Gobernanza Africano"

MI INDEPENDIENTE

#LIMPIEZA
```{r}
#########  LIMPIEZA
library(rio)
DATAJS=import("https://github.com/JhanpolS/variableindep/raw/master/GobernanzaPROMED__OFICIAL.xlsx")
str(DATAJS)
names(DATAJS)=gsub(" ","",names(DATAJS))
names(DATAJS)
table(DATAJS$RURALSECTOR,useNA ='always')
table(DATAJS$EDUCATION,useNA ='always')
#ME QUEDO SÓLO CON LAS FILAS QUE CONTIENEN LOS PROMEDIOS DE CADA PAÍS Y SUS VARIABLES
DATAJS=DATAJS[-(1:8),]
DATAJS=DATAJS[-(2:9),]
DATAJS=DATAJS[-(3:10),]
DATAJS=DATAJS[-(4:11),]
DATAJS=DATAJS[-(5:12),]
DATAJS=DATAJS[-(6:13),]
DATAJS=DATAJS[-(7:14),]
DATAJS=DATAJS[-(8:15),]
DATAJS=DATAJS[-(9:16),]
DATAJS=DATAJS[-(10:17),]
DATAJS=DATAJS[-(11:18),]
DATAJS=DATAJS[-(12:19),]
DATAJS=DATAJS[-(13:20),]
DATAJS=DATAJS[-(14:21),]
DATAJS=DATAJS[-(15:22),]
DATAJS=DATAJS[-(16:23),]
DATAJS=DATAJS[-(17:24),]
DATAJS=DATAJS[-(18:25),]
DATAJS=DATAJS[-(19:26),]
DATAJS=DATAJS[-(20:27),]
DATAJS=DATAJS[-(21:28),]
DATAJS=DATAJS[-(22:29),]
DATAJS=DATAJS[-(23:30),]
DATAJS=DATAJS[-(24:31),]
DATAJS=DATAJS[-(25:32),]
DATAJS=DATAJS[-(26:33),]
DATAJS=DATAJS[-(27:34),]
DATAJS=DATAJS[-(28:35),]
DATAJS=DATAJS[-(29:36),]
DATAJS=DATAJS[-(30:37),]
DATAJS=DATAJS[-(31:38),]
DATAJS=DATAJS[-(32:39),]
DATAJS=DATAJS[-(33:40),]
DATAJS=DATAJS[-(34:41),]
DATAJS=DATAJS[-(35:42),]
DATAJS=DATAJS[-(36:43),]
DATAJS=DATAJS[-(37:44),]
DATAJS=DATAJS[-(38:45),]
DATAJS=DATAJS[-(39:46),]
DATAJS=DATAJS[-(40:47),]
DATAJS=DATAJS[-(41:48),]
DATAJS=DATAJS[-(42:49),]
DATAJS=DATAJS[-(43:50),]
DATAJS=DATAJS[-(44:51),]
DATAJS=DATAJS[-(45:52),]
DATAJS=DATAJS[-(46:53),]
DATAJS=DATAJS[-(47:54),]
DATAJS=DATAJS[-(48:55),]
DATAJS=DATAJS[-(49:56),]
DATAJS=DATAJS[-(50:57),]
DATAJS=DATAJS[-(51:58),]
DATAJS=DATAJS[-(52:59),]
DATAJS=DATAJS[-(53:60),]
DATAJS=DATAJS[-(54:61),]
DATAJS=DATAJS[-(55:62),]
DATAJS=DATAJS[-(56:63),]

#Elimino columnas
DATAJS$Country_ISO=NULL
DATAJS$Year=NULL
DATAJS$OVERALLGOVERNANCE=NULL
names(DATAJS)

names(DATAJS)
names(DATAJS)=c("Pais","SAFETYandRULEOFLAW","RULEOFLAW","TRANSPARENCYandACCOUNTABILITY","PERSONALSAFETY","NATIONALSECURITY","PARTICIPATIONandHUMANRIGHTS","PARTICIPATION","RIGHTS","GENDER","SUSTAINABLEECONOMICOPPORTUNITY","PUBLICMANAGEMENT", "BUSINESSENVIRONMENT","INFRASTRUCTURE","RURALSECTOR","HUMANDEVELOPMENT","WELFARE","EDUCATION","HEALTH")




```
Cambiando el nombre de los países

```{r}
#LE CAMBIO EL NOMBRE A LOS PAÍSES
DATAJS[DATAJS$Pais=="Botswana",'Pais']="Botsuana"

DATAJS[DATAJS$Pais=="Cameroon",'Pais']="Camerun"

DATAJS[DATAJS$Pais=="Djibouti",'Pais']="Yibuti"

DATAJS[DATAJS$Pais=="Djibouti",'Pais']="Yibuti"
DATAJS[DATAJS$Pais=="Comoros",'Pais']="Comoras"
DATAJS[DATAJS$Pais=="Egypt",'Pais']="Egipto"
DATAJS[DATAJS$Pais=="Equatorial Guinea",'Pais']="Guinea ecuatorial"
DATAJS[DATAJS$Pais=="Ethiopia",'Pais']="Etiopia"
DATAJS[DATAJS$Pais=="Kenya",'Pais']="Kenia"

DATAJS[DATAJS$Pais=="Libya",'Pais']="Libia"
DATAJS[DATAJS$Pais=="Malawi",'Pais']="Malaui"
DATAJS[DATAJS$Pais=="Mauritius",'Pais']="Mauricio"
DATAJS[DATAJS$Pais=="Rwanda",'Pais']="Ruanda"
DATAJS[DATAJS$Pais=="São Tomé & Príncipe",'Pais']="Santo Tome y Principe"
DATAJS[DATAJS$Pais=="Sierra Leone",'Pais']="Sierra Leona"
DATAJS[DATAJS$Pais=="South Africa",'Pais']="Sudafrica"
DATAJS[DATAJS$Pais=="South Sudan",'Pais']="Sudan del Sur"
DATAJS[DATAJS$Pais=="Swaziland",'Pais']="Suazilandia"
DATAJS[DATAJS$Pais=="Tunisia",'Pais']="Tunez"
DATAJS[DATAJS$Pais=="ZImbabwe",'Pais']="Zimbabue"
DATAJS[DATAJS$Pais=="Algeria",'Pais']="Argelia"
DATAJS[DATAJS$Pais=="Central African Republic",'Pais']="Republica Centroafricana"
DATAJS[DATAJS$Pais=="Democratic Republic of Congo",'Pais']="Republica Democratica del Congo"

DATAJS[DATAJS$Pais=="Côte d'Ivoire",'Pais']="Costa de Marfil"

DATAJS[DATAJS$Pais=="Lesotho",'Pais']="Lesoto"

DATAJS[DATAJS$Pais=="Guinea-Bissau",'Pais']="Guinea Bisau"
DATAJS[DATAJS$Pais=="Morocco",'Pais']="Marruecos"
DATAJS[DATAJS$Pais=="Congo",'Pais']="Republica del Congo"

```

#Convierto a numérico y organizo la data
```{r}
DATAJS <- DATAJS[with(DATAJS, order(DATAJS$Pais)), ]

DATAJS[,c(2:15)]=lapply(DATAJS[,c(2:15)], as.numeric)
row.names(DATAJS)=NULL
DATAJS=DATAJS[-47,] #Elimino Sudán del Sur, a penas se creó en el 2011
row.names(DATAJS)=NULL
row.names(DATAJS)=DATAJS$Pais
#Elimino scores que no necesito
DATAJS=DATAJS[,-c(2,7,11,16)] # sin los Scores ni nombre de país.
DATAJS=na.omit(DATAJS) 
#Verifico la limpieza de mi data
str(DATAJS)
```

